
#### general settings

name: 01_IDN_DB_x2_scratch_JHTDB
use_tb_logger: true
model: IDN
distortion: sr
scale: 2
gpu_ids: [0]


#### datasets

datasets:
  train:
    name: JHTDB_VTK
    mode: GT3D
    set_type: vtk
    data_type: point
    dataroot_GT: 'E:/JHTDB/isotropic1024coarse/p' #'E:/JHTDB/isotropic1024coarse/p1' # path to training HR images
    dataroot_LQ: ~ # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 1
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_VTI1
    mode: GT3D
    set_type: vtk
    data_type: point
    field: pressure
    dataroot_GT: 'E:/JHTDB/isotropic1024coarse/p' # path to validation HR images 'E:/JHTDB/isotropic1024coarse/p1'
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader


#### network structures

network_IDN:
  which_model_G:
      subnet_type: DBNet
  in_nc: 1
  out_nc: 1
  k_size: 3
  block_num: 3
  scale: 2
  res_scale: 0.1
  init: xavier


#### path

path:
  pretrain_model_G: ~ # pretrain_model_IDN
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss

train:
  lr: !!float 2e-4
  beta1: 0.9
  beta2: 0.999
  niter: 5000 #500000 100set, 50 epoch
  warmup_iter: -1  # no warm up

  lr_scheme: ReduceLROnPlateau_Restart
  lr_factor: 0.3
  lr_patience: 10
  lr_threshold: 0.00001
  lr_steps: [100000, 200000, 300000, 400000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  manual_seed: 10

  val_freq: 1 #!!float 5e3

#  lambda_border: 1
#  lambda_fidelity_GTLR: 1
  lambda_fidelity_GTHR: 1
#  lambda_gradient_GTLR: 1
  lambda_gradient_GTHR: 1
  lambda_isosurface_similarity: 0.001
  weight_decay: !!float 1e-5
  gradient_clipping: 10


#### logger

logger:
  print_freq: 1 #100
  save_checkpoint_freq: !!float 5e3
