
#### general settings

name: 01_IRN_DB_x2_scratch_DAT1
use_tb_logger: true
model: IRN
distortion: sr
scale: 2
gpu_ids: [0]


#### datasets

datasets:
  train:
    name: DAT1
    mode: LQGT3D
    attr_id: 0
    type: tecplot
    dataroot_GT: 'E:\TestData\eta_processed\' #'H:/CVcodes/3d-SR/data' # path to training HR images
    dataroot_LQ: ~ # path to training reference LR images, not necessary, if not provided, LR images will be generated in dataloader

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 1
    GT_size: 144
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: val_VTI1
    mode: LQGT3D
    attr_id: 0
    type: tecplot
    dataroot_GT: 'E:\TestData\eta_processed\' # path to validation HR images
    dataroot_LQ: ~ # path to validation reference LR images, not necessary, if not provided, LR images will be generated in dataloader


#### network structures

network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 1
  out_nc: 1
  block_num: [2]
  scale: 2
  init: xavier


#### path

path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 2e-4
  beta1: 0.9
  beta2: 0.999
  niter: 5 #500000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [100000, 200000, 300000, 400000]
  lr_gamma: 0.5

  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  manual_seed: 10

  val_freq: 1 #!!float 5e3

  lambda_fit_forw: 4.
  lambda_rec_back: 1
  lambda_ce_forw: 1
  weight_decay_G: !!float 1e-5
  gradient_clipping: 10


#### logger

logger:
  print_freq: 1 #100
  save_checkpoint_freq: !!float 5e3
